{{- if .Values.istioGateway.enabled -}}
{{- $svcName := include "dify.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ template "dify.gateway.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "dify.gateway.fullname" . }}
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    {{- range .Values.istioGateway.hosts }}
      - "{{ .host }}"
    {{- end }}

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "dify.virtualService.fullname" . }}
spec:
  gateways:
    - mesh
    - {{ template "dify.gateway.fullname" . }}
  hosts:
    - "{{ $svcName }}"
  {{- range .Values.istioGateway.hosts }}
    - "{{ .host }}"
  {{- end }}
  http:
    - route:
      - destination:
          host: "{{ $svcName }}"
          subset: "master" 
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ template "dify.destinationRule.fullname" . }}
spec:
  host: "{{ $svcName }}"
  subsets:
    - name: "master"
      labels:
        app.kubernetes.io/name: "{{ $svcName }}"
{{- end }}