apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dify.nginx.fullname" . }}
  namespace: {{ include "dify.namespace" . }}
data:
  proxy.conf: |-
    {{- if .Values.proxy.proxyConf }}
      {{- .Values.proxy.proxyConf | nindent 4}}
    {{- else }}
      {{- include "dify.nginx.config.proxy" . | indent 4 }}
    {{- end }}
  nginx.conf: |-
    {{- if .Values.proxy.nginxConf }}
      {{- .Values.proxy.nginxConf | nindent 4}}
    {{- else }}
      {{- include "dify.nginx.config.nginx" . | indent 4 }}
    {{- end }}
  default.conf: |-
    {{- if .Values.proxy.defaultConf }}
      {{- .Values.proxy.defaultConf | nindent 4}}
    {{- else }}
      {{- include "dify.nginx.config.default" . | indent 4 }}
    {{- end }}
{{- range $key, $value := .Values.extraConfigFiles }}
  {{ $key }}: |-
{{ $value | indent 4 }}
{{- end }}