{{ if .Values.worker.autoscaling.enabled }}
apiVersion: {{ include "dify.hpa.apiVersion" . }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "dify.worker.fullname" . }}
  namespace: {{ include "dify.namespace" . }}
  labels:
{{- include "dify.labels" . | nindent 4 }}
    component: worker
    # app: {{ template "dify.worker.fullname" . }}
{{ include "dify.ud.labels" . | indent 4 }}
spec:
  {{- if .Values.worker.autoscaling.behavior }}
  behavior:
    {{- toYaml .Values.autoscaling.behavior | nindent 4 }}
  {{- end }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "dify.worker.fullname" . }}
  minReplicas: {{ .Values.worker.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.worker.autoscaling.maxReplicas }}
  metrics: {{- toYaml .Values.worker.autoscaling.metrics}}
{{- end }}
